name: Tiny workflow

on:
  pull_request:

jobs:
  release-comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
          echo ${{ secrets.SLACK_WEBHOOK }}
      -
        name: Run add-merged-label
        uses: tosite/release-confirmation-action@v0
        with:
          action: notify
          isDebug: 1
          channel: '#random'
          showReleasedPulls: 1
          releasedDays: 100
          slackWebhook: ${{ secrets.SLACK_WEBHOOK }}
